"""empty message

Revision ID: 100985bb744b
Revises: 9fb1dd2ce107
Create Date: 2024-12-27 01:08:44.747837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100985bb744b'
down_revision = '9fb1dd2ce107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('application_deadline')

    # ### end Alembic commands ###
