"""add is_active to user model

Revision ID: b3f513678fa3
Revises: 1036f4a692d0
Create Date: 2024-12-30 01:44:15.481887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f513678fa3'
down_revision = '1036f4a692d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('next_run', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('run_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('success_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('failure_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('average_runtime', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_successful_run', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('consecutive_failures', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_runtime', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_runtime', sa.Float(), nullable=True))

    with op.batch_alter_table('stipend', schema=None) as batch_op:
        batch_op.alter_column('summary',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('homepage_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('application_procedure',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('eligibility_criteria',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('application_deadline',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('open_for_applications',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('stipend', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('open_for_applications',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('application_deadline',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('eligibility_criteria',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('application_procedure',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('homepage_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('summary',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.drop_column('min_runtime')
        batch_op.drop_column('max_runtime')
        batch_op.drop_column('consecutive_failures')
        batch_op.drop_column('last_successful_run')
        batch_op.drop_column('average_runtime')
        batch_op.drop_column('failure_count')
        batch_op.drop_column('success_count')
        batch_op.drop_column('run_count')
        batch_op.drop_column('last_error')
        batch_op.drop_column('next_run')
        batch_op.drop_column('schedule')

    # ### end Alembic commands ###
