"""mig

Revision ID: c238d4acf443
Revises: da9748af77ee
Create Date: 2024-12-29 00:26:51.181283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c238d4acf443'
down_revision = 'da9748af77ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
